### PR TITLE
'rc' referenced before assignment in aur.py

### PR DESCRIPTION
**Pull request by rpuntaie**

### CODE REVIEW

**Comment by kewlfft** [comment]
Thanks for your contribution.
Are there any case where `rc` is not assigned any value later in the function?

**Comment by rpuntaie** [comment]
I came across this problem experimenting: I had packages empty.

**Comment by kewlfft** [comment]
Please describe into details the problem and how to reproduce it.

**Comment by rpuntaie** [comment]
I was playing to install archlinux using ansible.
The repo is now here:

https://github.com/rpuntaie/ansible-arch-linux

In `group_vars/all.yml` replace the `extra_aur_packages` block with:

```
extra_aur_packages: []
```

Then doing (as in the `README.md`):


```
ansible-galaxy install kewlfft.aur
ansible-playbook --ask-become-pass configure.yml
```

produces the Python error:

```
variable `rc` referenced before assignment
```

**Comment by rpuntaie** [comment]
Minimal ansible playbook to reproduce:

  ```
  ---
  # ansible-galaxy install kewlfft.aur
  - hosts: localhost
    name: reproduce rc referenced before assignment
    vars:
      extra_aur_packages: []
    tasks:
      - import_role: {name: kewlfft.aur}
      - name: install aur
        aur:
          name: "{{ extra_aur_packages }}"

  ```

**Comment by kewlfft** [comment]
I see you use an empty list and therefore `rc` is never defined. Thanks for the proposed fix. Then what do you want to achieve with an empty list ?

**Comment by rpuntaie** [comment]
Yes, but sometimes one does a local change, like for a test, making the variable empty and suddenly runs into a problem completely somewhere else. This additional one line, makes it just more robust, needing less effort from a user, less further investigation from many and less changes by many. And since we invested some time in this, why not make it fruitful. But it is your choice, of course. I just wanted to let you know.

**Comment by kewlfft** [comment]
I agree it has to be fixed I would add a line testing for empty list and exiting around there: https://github.com/kewlfft/ansible-aur/blob/592c6d9841674211f904cf9ea2a951fca3fd5a80/library/aur.py#L335
would it work?

**Comment by rpuntaie** [comment]
That packages is empty just produces a problem with `rc referenced before assignment`. The change I propose via this pull request solves the problem and I tested it. IMHO this proposed line should be there just by local logic of the function.

The resulting message `package(s) already installed` is OK for zero packages, too. The code can work through zero packages just like it does for any number, no need to make a special case out of it, or catch it early.

**Comment by kewlfft** [comment]
There is a section to test entry parameters rather than tweaking on the fly within the functions the different exceptions.
This is much easier to maintain.

**Comment by rpuntaie** [comment]
This does not allow empty lists, but I think it is useful to include empty lists. If-then-else are bad. They propagate. Now every user must also have a `when` clause.

**Comment by kewlfft** [comment]
I am aligning to pacman: `# pacman -S` returns the error message `no targets specified`

**Comment by rpuntaie** [comment]
A CLI command can give feedback. I wouldn't call it is an error message to say 'no target specified'. You could create a specific message telling about 0 packages specified, too. But an error in this case just produces effort without any reason.

**Comment by kewlfft** [comment]
The command `pacman -S` not only gives feedback but raises error 1 as you could check, if you think pacman should  avoid unnecessary checks and speed up scripts you may have a point and I will follow.

**Comment by rpuntaie** [comment]
It's no big deal. Just my two cent. You decide.

**Comment by rpuntaie** [comment]
Since you have not yet close this, I take the chance to further help to make this solution better.

So far we did not achieve any change of behavior of the software.
Only the message has changed.

In mathematics, that deals with information processing,
those who like the topic, have invented 

- the 0 to avoid if-then-else
- infinity to defer decision (when to stop)

You can achieve both with my proposal:

- no if-then-else in all the software that uses yours
- defer the decision to provide or not provide packages
  along a arbitrarily large (=infinite) software hierarchy to the final user

You don't need to do what pacman did. Pacman did wrong in this point. yay realized that.

**Comment by kewlfft** [comment]
I let you raise this to [aur-general@lists.archlinux.org](https://lists.archlinux.org/listinfo/aur-general) and will follow their recommendation.

**Comment by kewlfft** [comment]
Error message has been corrected thanks for your contribution, no agreement has been reached with TUs on the change of _pacman_ according to this [thread](https://lists.archlinux.org/pipermail/aur-general/2021-January/036092.html).

**Comment by rpuntaie** [comment]
For pacman my patch is quite useless. I just made it because

-  based on right principles
- and because you made a dependency on pacman

I have not expected my patch to go into pacman.
Why should they make a change on a product used so often as pacman
and possibly break some private scripts.
I would not do it either, not even if violating a principle of mine.

But in the case of ansible.aur,
we were fixing a bug,
and my proposal would have been a better fix.
I know, "better" is relative.

Generally it is better, though, not to say "X does so, because Y does so".
It just creates noise.

I made noise because you made the dependency on pacman
and I would have liked ansible.aur to accept empty variables.

**Pull request closed without merging**
