### PR TITLE
fix quoting of package name

### PR DESCRIPTION
**Pull request by hvariant**
when installing packages such as lib32-libstdc++5

### CODE REVIEW

**Comment by kewlfft** [comment]
thanks for your contribution, quote is in urllib.parse, can you use urllib.parse module instead?

**Comment by hvariant** [comment]
sorry, I misread the documentation

**Comment by hvariant** [comment]
lemme fix it

**Comment by kewlfft** [comment]
have you tested it successfully ?

**Comment by hvariant** [comment]
wait, it seems that in Python 2 it's urllib.quote, and they moved the function to urllib.parse.quote in Python 3

**Comment by kewlfft** [comment]
yes and this is python 3

**Comment by hvariant** [comment]
oh okay, I assume the code will work but I can do some more local testing in a bit

**Comment by kewlfft** [comment]
yes please

**Comment by hvariant** [comment]
Okay the change is working for me, here are the relevant bits from my playbook result:
```
TASK [add aur_builder user] ******************************************************************************************************************************************************************
ok: [vm-my-archbox.ir.local] => {"append": false, "changed": false, "comment": "", "group": 998, "home": "/home/aur_builder", "move_home": false, "name": "aur_builder", "shell": "/bin/bash", "state": "present", "uid": 1001}

TASK [allow aur_builder to run sudo without password] ****************************************************************************************************************************************
ok: [vm-my-archbox.ir.local] => {"backup": "", "changed": false, "msg": ""}

TASK [install lib32-libstdc++5 from AUR] *****************************************************************************************************************************************************
ok: [vm-my-archbox.ir.local] => {"changed": false, "helper": "makepkg", "msg": "package(s) already installed", "rc": 0}
``` 

and the playbook:
```
- name: add aur_builder user
  user:
    name: aur_builder
    group: wheel
  become: yes
  become_method: sudo

- name: allow aur_builder to run sudo without password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: yes
  become_method: sudo

- name: install lib32-libstdc++5 from AUR
  aur:
    use: makepkg
    name:
      - lib32-libstdc++5
  become: yes
  become_method: sudo
  become_user: aur_builder
```

**Comment by hvariant** [comment]
thank you @kewlfft for merging

**Pull request merged**
