### PR TITLE
Add support for refresh package

### PR DESCRIPTION
**Pull request by assapir**
Should add support for refreshing the local cache as part of the current run.

### CODE REVIEW

**Comment by assapir** [comment]
Was tested with yay.

**Comment by gotmax23** [comment]
@kewlfft wrote:

> Can you show me where `--y` is described in yay's documentation and it needs to be supported by the majority of the other helpers to be introduced. Are the other helpers following the same syntax?

@assapir wrote:
> It's part of pacman syntax, same as `-u`

I think it should be `-y` or `--refresh` not `--y`.

\-[`man pacman`][1]

@assapir wrote:

> Then `full system update` isn't currect.

So you're saying that you want to be able to run the equivalent of `$helper -Syu with this`, correct? In other words, currently, it is possible to update packages but not update the package cache beforehand.

[1]: https://archlinux.org/pacman/pacman.8.html

**Comment by gotmax23** [comment]
Hi @assapir,

> > So you're saying that you want to be able to run the equivalent of `$helper -Syu with this`, correct? In other words, currently, it is possible to update packages but not update the package cache beforehand.
> 
> Exactly.

Okay, I am glad we're on the same page. Now that you explained the usecase, it makes more sense to me. We will have to see what @kewlfft thinks.

> There is also anther place (on `update`) where it using the shorthand and not the full flag name.

I am not arguing for or against using shorthand. `--y` is just not a valid flag according to `man pacman`. If `yay` or another AUR helper interprets that differently, I do not think that is the intended behavior.

Thanks,
Maxwell

**Comment by gotmax23** [comment]
גם, ראיתי שאתה ישראלי. עברית היא השפה השניה שלי. זא מגניב לראות אנשים אחרים שמדברים עברית על גיטהוב!

**Comment by assapir** [comment]
> Also, make sure that your code is idempotent.

Yes, this is idempotent. nothing happens if you try to refresh if the packages db is already up-to-date.

I fix the flag. trying to use the full flag (aka `--refresh`) doesn't work and fails.

**Pull request merged**
