### PR TITLE
Add pamac support

### PR DESCRIPTION
**Pull request by edmeister**

### CODE REVIEW

**Comment by kewlfft** [comment]
do you confirm `pamac` has `--aur` option as you indicated? I would need to look at it again, from what I remember `pamac` does not adhere to arch good practices.

**Comment by edmeister** [comment]
It's the default package manager on Manjaro and works fine with AUR.

**Comment by kewlfft** [comment]
Potential partial upgrade issues were identified in the past with `pamac`. If you can find good comments about it from Arch TUs I will happily add it to the list.

**Comment by kewlfft** [comment]
closing after 1 month without confirmation, see Arch wiki for information about pamac known issues.

**Pull request closed without merging**
