### PR TITLE
yay doesn't refer to either LC_ALL or LANGUAGE

### PR DESCRIPTION
**Pull request by octaltree**
https://github.com/Jguer/yay/blob/5c11c01d853835f24edbfd0a242dc3a73d537547/main.go#L20-L30
yay seems to look at LC_MESSAGES or LANG, so I added LC_MESSAGES=C. Please check.

### CODE REVIEW

**Comment by kewlfft** [comment]
`LC_ALL=C` is supposed to override the values of any other `LC_*` environment variables

**Comment by octaltree** [comment]
yay only sees LANG as a fallback for LC_MESSAGES, so LC_ALL and LANGUAGE are not enough

## my environment
uname -a: `Linux coorie 5.10.56-1-MANJARO #1 SMP PREEMPT Thu Aug 5 10:51:27 UTC 2021 x86_64 GNU/Linux`
zsh --version: `zsh 5.8 (x86_64-pc-linux-gnu)`
cat /etc/locale.conf:
```
LANG=ja_JP.UTF-8
```
and it doesn't have any locale.conf in $XDG_CONFIG_HOME/.
locale:
```
LANG=ja_JP.UTF-8
LC_CTYPE="ja_JP.UTF-8"
LC_NUMERIC="ja_JP.UTF-8"
LC_TIME="ja_JP.UTF-8"
LC_COLLATE="ja_JP.UTF-8"
LC_MONETARY="ja_JP.UTF-8"
LC_MESSAGES="ja_JP.UTF-8"
LC_PAPER="ja_JP.UTF-8"
LC_NAME="ja_JP.UTF-8"
LC_ADDRESS="ja_JP.UTF-8"
LC_TELEPHONE="ja_JP.UTF-8"
LC_MEASUREMENT="ja_JP.UTF-8"
LC_IDENTIFICATION="ja_JP.UTF-8"
LC_ALL=
```
locale --version:
```
locale (GNU libc) 2.33
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
作者 Ulrich Drepper。
```
cat ~/e.go:
```
package main

import (
	"fmt"
	"os"
)

func main(){
    fmt.Println(os.Getenv("LANG"));
    fmt.Println(os.Getenv("LC_ALL"));
    fmt.Println(os.Getenv("LC_MESSAGES"));
    fmt.Println(os.Getenv("LANGUAGE"));
}
```
go run ~/e.go:
```
ja_JP.UTF-8



```

systemd-localed.service is loaded but not running. what is it

## With additional env
env LANG=C LC_ALL=C locale:
```
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```
env LANG=C LC_ALL=C go run e.go:
```
C
C


```
env LANG=C LC_ALL=C LC_MESSAGES=C go run e.go:
```
C
C
C

```

If you follow the [arch wiki](https://wiki.archlinux.org/title/Locale) and look at [gettext](https://www.gnu.org/software/gettext/manual/gettext.html#Locale-Environment-Variables), you will see that LC_ALL is overwritten, but I can't find anything in [locale(5)](https://man7.org/linux/man-pages/man5/locale.5.html) or [locale(7)](https://man7.org/linux/man-pages/man7/locale.7.html) that says the environment variable is overwritten. setlocale(3) contains the following statement:
>If locale is an empty string, "", each part of the locale that
>should be modified is set according to the environment variables.
>The details are implementation-dependent.  For glibc, first
>(regardless of category), the environment variable LC_ALL is
>inspected, next the environment variable with the same name as
>the category (see the table above), and finally the environment
>variable LANG.  The first existing environment variable is used.
>If its value is not a valid locale specification, the locale is
>unchanged, and setlocale() returns NULL.
https://code.woboq.org/userspace/glibc/locale/setlocale.c.html#setlocale

There is no process in /etc/profile.d/locale.sh to override the environment variable either, and maybe this means that the application should write a fallback to LC_ALL?

**Comment by kewlfft** [comment]
In your outputs I can't see to what variable each C corresponds to.

**Comment by octaltree** [comment]
I made a mistake when writing the test. I wrote tests for LC_ALL and LANG even though this wrapper only sets for LC_ALL and LANGUAGE.

cat e.go
```
package main

import (
	"fmt"
	"os"
)

func main(){
    fmt.Printf("LANG\t'%s'\n", os.Getenv("LANG"));
    fmt.Printf("LC_ALL\t'%s'\n", os.Getenv("LC_ALL"));
    fmt.Printf("LC_MESSAGES\t'%s'\n", os.Getenv("LC_MESSAGES"));
    fmt.Printf("LANGUAGE\t'%s'\n", os.Getenv("LANGUAGE"));
}
```
go run e.go
```
LANG    'ja_JP.UTF-8'
LC_ALL  ''
LC_MESSAGES     ''
LANGUAGE        ''
```
env LANGUAGE=C LC_ALL=C locale
```
LANG=ja_JP.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```
env LANGUAGE=C LC_ALL=C go run e.go
```
LANG    'ja_JP.UTF-8'
LC_ALL  'C'
LC_MESSAGES     ''
LANGUAGE        'C'
```
env LANGUAGE=C LC_ALL=C LC_MESSAGES=C go run e.go
```
LANG    'ja_JP.UTF-8'
LC_ALL  'C'
LC_MESSAGES     'C'
LANGUAGE        'C'
```
env LANGUAGE=C LC_ALL=C LANG=C go run e.go
```
LANG    'C'
LC_ALL  'C'
LC_MESSAGES     ''
LANGUAGE        'C'
```

**Comment by kewlfft** [comment]
good, everything works as expected

**Comment by octaltree** [comment]
>env LANGUAGE=C LC_ALL=C go run e.go
>```
>LANG    'ja_JP.UTF-8'
>LC_ALL  'C'
>LC_MESSAGES     ''
>LANGUAGE        'C'
>```
This result indicates that yay speaks Japanese and does not match messages such as "nothing to do". Isn't that right?

**Comment by kewlfft** [comment]
not sure how yay interprets it

**Comment by octaltree** [comment]
## yay
yay --version
```
yay v10.3.1 - libalpm v13.0.0
```
yay -S --noconfirm --needed --cleanafter -u
```
:: システム全体の更新を開始...
警告: manjaro-hello: ローカル (0.6.7-2) の方が extra よりも最新です (0.6.6-6)
 何も行うことがありません
:: データベースからアップデートを検索...
:: AUR からアップデートを検索...
 -> manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-6)
 -> 存在しない AUR パッケージ:  linux-latest
 -> メンテナが存在しない AUR パッケージ:  hts-engine
 -> 古いバージョンのフラグが立てられた AUR パッケージ:  luacheck
 何もすることがありません
```

env LANGUAGE=C LC_ALL=C yay -S --noconfirm --needed --cleanafter -u
```
:: Starting full system upgrade...
warning: manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-6)
 there is nothing to do
:: データベースからアップデートを検索...
:: AUR からアップデートを検索...
 -> manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-6)
 -> 存在しない AUR パッケージ:  linux-latest
 -> メンテナが存在しない AUR パッケージ:  hts-engine
 -> 古いバージョンのフラグが立てられた AUR パッケージ:  luacheck
 何もすることがありません
```

env LANGUAGE=C LC_ALL=C LC_MESSAGES=C yay -S --noconfirm --needed --cleanafter -u
```
:: Starting full system upgrade...
warning: manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-6)
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-6)
 -> Missing AUR Packages:  linux-latest
 -> Orphaned AUR Packages:  hts-engine
 -> Flagged Out Of Date AUR Packages:  luacheck
 there is nothing to do
```
env LANGUAGE=C LC_ALL=C yay -S --noconfirm --needed --cleanafter -u --aur
```
:: AUR からアップデートを検索...
 -> 存在しない AUR パッケージ:  linux-latest
 -> メンテナが存在しない AUR パッケージ:  hts-engine
 -> 古いバージョンのフラグが立てられた AUR パッケージ:  luacheck
 何もすることがありません
```

## pacman
sudo pacman -S --noconfirm --needed -u
```
:: システム全体の更新を開始...
警告: manjaro-hello: ローカル (0.6.7-2) の方が extra よりも最新です (0.6.6-6)
 何も行うことがありません
```
env LANGUAGE=C LC_ALL=C sudo pacman -S --noconfirm --needed -u
```
:: Starting full system upgrade...
warning: manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-6)
 there is nothing to do
```

These results show that pacman refers to LC_ALL or LANGUAGE, but yay is not affected by them.

**Comment by kewlfft** [comment]
Can you check if other AUR helpers have the same behavior and in this case I will investigate otherwise this is a `yay` issue and we close the PR.

**Comment by octaltree** [comment]
Other than yay, aur helpers have behavior based on or mimicking gettext and refer to LC_ALL, LANG, LANGUAGE.

## makepkg
makepkg --help| head -n 3
```
makepkg (pacman) 6.0.0

pacman で使用するための互換性のあるパッケージを作成
```
env LC_ALL=C makepkg --help| head -n 3
```
makepkg (pacman) 6.0.0

Make packages compatible for use with pacman
```

LC_ALL is referenced.

## paru
I installed with `yay -S paru-git`.
paru -Su --aur
```
:: AUR の更新を確認しています
:: 開発の更新を確認しています
:: AUR にないパッケージ: linux-latest
:: out of date とマークされている: luacheck
:: 孤児: hts-engine
 何もすることがありません
```
env LC_ALL=C paru -Su --aur
```
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: packages not in the AUR: linux-latest
:: marked out of date: luacheck
:: orphans: hts-engine
 there is nothing to do
```
LC_ALL is referenced.

## pacaur
pacaur is in status archived.
I installed with `yay -S aurman-git`.
pacaur --help | head -n 3
```
使い方: pacaur <オペレーション> [オプション] [パッケージ] -- pacaur(8) も参照
オペレーション:
 pacmanの拡張
```
env LC_ALL=C pacaur --help | head -n 3
```
usage:  pacaur <operation> [options] [target(s)] -- See also pacaur(8)
operations:
 pacman extension
```
LC_ALL is referenced.

## trizen
trizen is only available in English. https://github.com/trizen/trizen/issues/49

## pikaur
I installed with `yay -S pikaur-git`.
pikaur -Su --aur
```
:: AUR 全体の更新を開始...
リポジトリのパッケージデータベースを読み込み中...
ローカルのパッケージデータベースを読み込み中...
AUR のパッケージ情報を読み込み中...
:: 警告: 次のパッケージは AUR に存在しません:
    linux-latest
:: 実行すべき処理はありません。
```
env LC_ALL=C pikaur -Su --aur
```
:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
:: warning: Following package cannot be found in AUR:
    linux-latest
:: Nothing to do.
```
LC_ALL is referenced.

## aurman
I installed with `yay -S aurman`.
aurman -Su --aur
```
:: システム全体の更新を開始...
警告: manjaro-hello: ローカル (0.6.7-2) の方が extra よりも最新です (0.6.6-6)
 何も行うことがありません

~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: linux-latest-5.10-1
~~ calculating solutions...
:: nothing to do... everything is up to date
```

env LC_ALL=C aurman -Su --aur
```
:: Starting full system upgrade...
warning: manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-6)
 there is nothing to do

~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: linux-latest-5.10-1
~~ calculating solutions...
:: nothing to do... everything is up to date ```
```

env LC_ALL=ja_JP.UTF-8 LANG=ja_JP.UTF-8 LC_MESSAGES=ja_JP.UTF_8 LANGUAGE=ja_JP.UTF-8 aurman -Su --aur
```
:: システム全体の更新を開始...
警告: manjaro-hello: ローカル (0.6.7-2) の方が extra よりも最新です (0.6.6-6)
 何も行うことがありません

~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: linux-latest-5.10-1
~~ calculating solutions...
:: nothing to do... everything is up to date
```
aurman is only available in English. It appears that `--aur` is ignored


I should report it to yay because it ignores LC_ALL even though it uses gotext. But at the same time I think this wrapper is to absorb the difference.

**Comment by kewlfft** [comment]
`But at the same time I think this wrapper is to absorb the difference.` I disagree, this helper is as generic as possible it does not intend to correct individual tool behavior

**Pull request closed without merging**
