### PR TITLE
Added ignore_arch option for makepkg

### PR DESCRIPTION
**Pull request by neilmunday**

### CODE REVIEW

**Comment by kewlfft** [comment]
thanks for the commit.
I would stick to _makepkg_ and call it `ignorearch`without _

**Comment by neilmunday** [comment]
Hi. Thanks for looking at my pull request. I only planned the new option for `makepkg` for now. I personally liked the underscore to make it easier to read and to fit with your existing "skip_XXX" options.

**Comment by neilmunday** [comment]
Just realised that I forgot to update the README as well.

**Comment by kewlfft** [comment]
done

**Comment by neilmunday** [comment]
Looks good to me 👍

**Pull request merged**
