### PR TITLE
Check mode support, skip pgp check, etc. pp.

### PR DESCRIPTION
**Pull request by ckotte**
plus improved messages, visible in verbose mode, and renaming of internal helper to makepkg. See commit messages for details.

### CODE REVIEW

**Comment by kewlfft** [comment]
Thanks for these very good commits

**Comment by ckotte** [comment]
Welcome :)

**Comment by ckotte** [comment]
Btw. Do you use all helpers or did you simply added (the most popular ones) so that everybody can choose what he/she prefers?

**Comment by kewlfft** [comment]
I added popular ones, may remove yaourt which is not secure though

**Comment by ckotte** [comment]
Ok. I still use pacaur despite it's not maintained anymore. I had some strange bugs with pikaur (that were fixed), but the layout in .cache/pikaur is a bit strange and I may need to adapt my cache cleanup scripts...

**Comment by kewlfft** [comment]
I tested most of them and recently have been using aurman which is recent but seem pretty good and actively developped

**Pull request merged**
