### PR TITLE
Embed module in role

### LINKED ISSUE #28: Wrap the module in a role
What about wrapping this module into a role and publish it to ansible galaxy? So that end users or other role developers can easily consume it.

See https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#embedding-modules-and-plugins-in-roles

For end users, they can do something like:

```yml
# playbook.yml
- hosts: localhost
  roles:
  - name: kewlfft.aur
  tasks:
  - aur:
      name: xxx
```

For role developers:

```yml
# meta/main.yml
dependencies:
- kewlfft.aur
```

```yml
# tasks/main.yml
- aur:
    name: xxx
```

### PR DESCRIPTION
**Pull request by pallxk**
Here is the change for reference to embed a module in a role.

Fix #28.

### CODE REVIEW

**Comment by kewlfft** [comment]
I am not familiar with Galaxy, beside this additional file what is needed to make it available?

**Comment by pallxk** [comment]
As a note, I see that [AUR package](https://aur.archlinux.org/packages/ansible-aur-git/) for this is referencing aur.py in the project root, see [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ansible-aur-git). So either we need to keep a symlink for aur.py at project root or we need to update PKGBUILD if this is merged.

**Comment by panchoh** [comment]
Hi!
I'm the maintainer of the AUR package, and I'll be happy to quickly update the PKGBUILD to handle the new path.

Nice idea, this PR!

Cheers,

**Comment by kewlfft** [comment]
Can you also amend the README to explain the new manual installation and the new galaxy integration?

**Comment by pallxk** [comment]
Sure. I've updated the README for your review just now.

Note that manual installation via 
```
git clone https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur
```
doesn't change even if aur.py is moved into library subdirectory.

**Comment by panchoh** [comment]
I've updated the AUR package to reflect the change.

**Pull request merged**
